version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: wow_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=wow
    restart: unless-stopped

volumes:
  mongodb_data:
